"""add faculty_courses table

Revision ID: 18b3670e77d7
Revises: 1a9440638221
Create Date: 2026-02-12 11:17:59.638908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b3670e77d7'
down_revision: Union[str, None] = '1a9440638221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'course_id', 'section_id', 'semester_id', name='uq_faculty_course_section_semester')
    )
    op.create_index(op.f('ix_faculty_courses_course_id'), 'faculty_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_faculty_courses_faculty_id'), 'faculty_courses', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_faculty_courses_id'), 'faculty_courses', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_courses_section_id'), 'faculty_courses', ['section_id'], unique=False)
    op.create_index(op.f('ix_faculty_courses_semester_id'), 'faculty_courses', ['semester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_courses_semester_id'), table_name='faculty_courses')
    op.drop_index(op.f('ix_faculty_courses_section_id'), table_name='faculty_courses')
    op.drop_index(op.f('ix_faculty_courses_id'), table_name='faculty_courses')
    op.drop_index(op.f('ix_faculty_courses_faculty_id'), table_name='faculty_courses')
    op.drop_index(op.f('ix_faculty_courses_course_id'), table_name='faculty_courses')
    op.drop_table('faculty_courses')
    # ### end Alembic commands ###
