"""Add elective_group_id to Curriculum

Revision ID: 2a0f37eaf0c2
Revises: add_faculty_leave_time_slots
Create Date: 2026-03-08 22:49:43.874090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0f37eaf0c2'
down_revision: Union[str, None] = 'add_faculty_leave_time_slots'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum', sa.Column('elective_group_id', sa.Integer(), nullable=True))
    op.alter_column('curriculum', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_curriculum_dept_year_sem_course', 'curriculum', type_='unique')
    op.create_index(op.f('ix_curriculum_elective_group_id'), 'curriculum', ['elective_group_id'], unique=False)
    op.create_unique_constraint('uq_curriculum_dept_year_sem_course_group', 'curriculum', ['department_id', 'year_level', 'semester_type', 'course_id', 'elective_group_id'])
    op.create_foreign_key(None, 'curriculum', 'elective_groups', ['elective_group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_faculty_leaves_start_time_slot_id', 'faculty_leaves', type_='foreignkey')
    op.drop_constraint('fk_faculty_leaves_end_time_slot_id', 'faculty_leaves', type_='foreignkey')
    op.create_foreign_key(None, 'faculty_leaves', 'time_slots', ['end_time_slot_id'], ['id'])
    op.create_foreign_key(None, 'faculty_leaves', 'time_slots', ['start_time_slot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculty_leaves', type_='foreignkey')
    op.drop_constraint(None, 'faculty_leaves', type_='foreignkey')
    op.create_foreign_key('fk_faculty_leaves_end_time_slot_id', 'faculty_leaves', 'time_slots', ['end_time_slot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_faculty_leaves_start_time_slot_id', 'faculty_leaves', 'time_slots', ['start_time_slot_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'curriculum', type_='foreignkey')
    op.drop_constraint('uq_curriculum_dept_year_sem_course_group', 'curriculum', type_='unique')
    op.drop_index(op.f('ix_curriculum_elective_group_id'), table_name='curriculum')
    op.create_unique_constraint('uq_curriculum_dept_year_sem_course', 'curriculum', ['department_id', 'year_level', 'semester_type', 'course_id'])
    op.alter_column('curriculum', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('curriculum', 'elective_group_id')
    # ### end Alembic commands ###
