"""Initial migration with String Enums

Revision ID: 516deebcede1
Revises: 
Create Date: 2026-02-05 01:47:05.534228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '516deebcede1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('rule_definition', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_hard', sa.Boolean(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("constraint_type IN (\n                'NO_FACULTY_CLASH', 'NO_ROOM_CLASH', 'NO_STUDENT_CLASH',\n                'WORKLOAD_LIMIT', 'ROOM_CAPACITY', 'LAB_REQUIREMENT',\n                'PREFERENCE_TIME', 'PREFERENCE_DAY', 'MAX_CONSECUTIVE',\n                'MIN_BREAK', 'MAX_COMMUTE', 'ELECTIVE_NO_CLASH'\n            )", name='check_constraint_type_valid'),
    sa.CheckConstraint('priority >= 0 AND priority <= 1000', name='check_priority_range'),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name='check_weight_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraints_id'), 'constraints', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('elective_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('participating_department_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_elective_groups_id'), 'elective_groups', ['id'], unique=False)
    op.create_table('institutional_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('is_hard_constraint', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('applies_to_departments', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('applies_to_years', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_institutional_rules_id'), 'institutional_rules', ['id'], unique=False)
    op.create_index(op.f('ix_institutional_rules_is_active'), 'institutional_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_institutional_rules_rule_type'), 'institutional_rules', ['rule_type'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=50), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('has_projector', sa.Boolean(), nullable=True),
    sa.Column('has_lab_equipment', sa.Boolean(), nullable=True),
    sa.Column('has_ac', sa.Boolean(), nullable=True),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("room_type IN ('classroom', 'lab', 'auditorium', 'seminar_hall')", name='check_room_type_valid'),
    sa.CheckConstraint('capacity > 0', name='check_capacity_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_rooms_building'), 'rooms', ['building'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_break', sa.Boolean(), nullable=True),
    sa.Column('slot_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')", name='check_day_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_slots_id'), 'time_slots', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('theory_hours', sa.Integer(), nullable=False),
    sa.Column('lab_hours', sa.Integer(), nullable=False),
    sa.Column('tutorial_hours', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('course_category', sa.String(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=True),
    sa.Column('elective_group_id', sa.Integer(), nullable=True),
    sa.Column('requires_lab', sa.Boolean(), nullable=True),
    sa.Column('min_room_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('credits > 0', name='check_credits_positive'),
    sa.CheckConstraint('lab_hours >= 0', name='check_lab_hours_nonnegative'),
    sa.CheckConstraint('theory_hours + lab_hours + tutorial_hours > 0', name='check_hours_positive'),
    sa.CheckConstraint('theory_hours >= 0', name='check_theory_hours_nonnegative'),
    sa.CheckConstraint('tutorial_hours >= 0', name='check_tutorial_hours_nonnegative'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['elective_group_id'], ['elective_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('batch_year_start', sa.Integer(), nullable=False),
    sa.Column('batch_year_end', sa.Integer(), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('dedicated_room_id', sa.Integer(), nullable=True),
    sa.Column('class_advisor_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dedicated_room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_dedicated_room_id'), 'sections', ['dedicated_room_id'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_algorithm', sa.String(length=20), nullable=True),
    sa.Column('generation_time_seconds', sa.Float(), nullable=True),
    sa.Column('generation_config', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("generation_algorithm IS NULL OR generation_algorithm IN ('GA', 'SA', 'HYBRID', 'CSP_GREEDY')", name='check_algorithm_valid'),
    sa.CheckConstraint("status IN ('generating', 'completed', 'failed', 'archived')", name='check_status_valid'),
    sa.CheckConstraint('conflict_count >= 0', name='check_conflict_count_positive'),
    sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 1)', name='check_quality_score_range'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetables_id'), 'timetables', ['id'], unique=False)
    op.create_index(op.f('ix_timetables_is_published'), 'timetables', ['is_published'], unique=False)
    op.create_index(op.f('ix_timetables_semester_id'), 'timetables', ['semester_id'], unique=False)
    op.create_index(op.f('ix_timetables_status'), 'timetables', ['status'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('slot_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("conflict_type IN (\n                'ROOM_CLASH', 'FACULTY_CLASH', 'STUDENT_CLASH',\n                'CAPACITY_VIOLATION', 'LAB_REQUIREMENT_VIOLATION',\n                'ELECTIVE_CLASH', 'CONSTRAINT_VIOLATION'\n            )", name='check_conflict_type_valid'),
    sa.CheckConstraint("severity IN ('HIGH', 'MEDIUM', 'LOW')", name='check_severity_valid'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_conflict_type'), 'conflicts', ['conflict_type'], unique=False)
    op.create_index(op.f('ix_conflicts_id'), 'conflicts', ['id'], unique=False)
    op.create_index(op.f('ix_conflicts_is_resolved'), 'conflicts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_conflicts_timetable_id'), 'conflicts', ['timetable_id'], unique=False)
    op.create_table('course_batching_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('num_batches', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('batch_size > 0', name='check_batch_size_positive'),
    sa.CheckConstraint('num_batches >= 1 AND num_batches <= 10', name='check_num_batches_valid'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'semester_id', name='uq_batching_course_sem')
    )
    op.create_index(op.f('ix_course_batching_config_course_id'), 'course_batching_config', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_batching_config_id'), 'course_batching_config', ['id'], unique=False)
    op.create_index(op.f('ix_course_batching_config_semester_id'), 'course_batching_config', ['semester_id'], unique=False)
    op.create_table('course_elective_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elective_group_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('assigned_room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['elective_group_id'], ['elective_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elective_group_id', 'semester_id', 'course_id', name='uq_elective_assignment_group_sem_course')
    )
    op.create_index(op.f('ix_course_elective_assignments_course_id'), 'course_elective_assignments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_elective_assignments_elective_group_id'), 'course_elective_assignments', ['elective_group_id'], unique=False)
    op.create_index(op.f('ix_course_elective_assignments_id'), 'course_elective_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_course_elective_assignments_semester_id'), 'course_elective_assignments', ['semester_id'], unique=False)
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('year_level', sa.Integer(), nullable=False),
    sa.Column('semester_type', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('year_level >= 1 AND year_level <= 4', name='check_year_level_valid'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'year_level', 'semester_type', 'course_id', name='uq_curriculum_dept_year_sem_course')
    )
    op.create_index(op.f('ix_curriculum_course_id'), 'curriculum', ['course_id'], unique=False)
    op.create_index(op.f('ix_curriculum_department_id'), 'curriculum', ['department_id'], unique=False)
    op.create_index(op.f('ix_curriculum_id'), 'curriculum', ['id'], unique=False)
    op.create_table('faculty_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('replacement_faculty_id', sa.Integer(), nullable=True),
    sa.Column('impact_analysis', sa.JSON(), nullable=True),
    sa.Column('resolution_details', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['replacement_faculty_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_leaves_faculty_id'), 'faculty_leaves', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_faculty_leaves_id'), 'faculty_leaves', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_leaves_semester_id'), 'faculty_leaves', ['semester_id'], unique=False)
    op.create_index(op.f('ix_faculty_leaves_status'), 'faculty_leaves', ['status'], unique=False)
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('start_slot_id', sa.Integer(), nullable=False),
    sa.Column('duration_slots', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('primary_faculty_id', sa.Integer(), nullable=True),
    sa.Column('assisting_faculty_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('batch_number IS NULL OR batch_number > 0', name='check_batch_number_positive'),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='check_day_of_week_valid'),
    sa.CheckConstraint('duration_slots >= 1 AND duration_slots <= 5', name='check_duration_slots_valid'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_slot_id'], ['time_slots.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slots_id'), 'timetable_slots', ['id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_is_locked'), 'timetable_slots', ['is_locked'], unique=False)
    op.create_index(op.f('ix_timetable_slots_primary_faculty_id'), 'timetable_slots', ['primary_faculty_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_room_id'), 'timetable_slots', ['room_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_section_id'), 'timetable_slots', ['section_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_start_slot_id'), 'timetable_slots', ['start_slot_id'], unique=False)
    op.create_index(op.f('ix_timetable_slots_timetable_id'), 'timetable_slots', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_slots_timetable_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_start_slot_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_section_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_room_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_primary_faculty_id'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_is_locked'), table_name='timetable_slots')
    op.drop_index(op.f('ix_timetable_slots_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index(op.f('ix_faculty_leaves_status'), table_name='faculty_leaves')
    op.drop_index(op.f('ix_faculty_leaves_semester_id'), table_name='faculty_leaves')
    op.drop_index(op.f('ix_faculty_leaves_id'), table_name='faculty_leaves')
    op.drop_index(op.f('ix_faculty_leaves_faculty_id'), table_name='faculty_leaves')
    op.drop_table('faculty_leaves')
    op.drop_index(op.f('ix_curriculum_id'), table_name='curriculum')
    op.drop_index(op.f('ix_curriculum_department_id'), table_name='curriculum')
    op.drop_index(op.f('ix_curriculum_course_id'), table_name='curriculum')
    op.drop_table('curriculum')
    op.drop_index(op.f('ix_course_elective_assignments_semester_id'), table_name='course_elective_assignments')
    op.drop_index(op.f('ix_course_elective_assignments_id'), table_name='course_elective_assignments')
    op.drop_index(op.f('ix_course_elective_assignments_elective_group_id'), table_name='course_elective_assignments')
    op.drop_index(op.f('ix_course_elective_assignments_course_id'), table_name='course_elective_assignments')
    op.drop_table('course_elective_assignments')
    op.drop_index(op.f('ix_course_batching_config_semester_id'), table_name='course_batching_config')
    op.drop_index(op.f('ix_course_batching_config_id'), table_name='course_batching_config')
    op.drop_index(op.f('ix_course_batching_config_course_id'), table_name='course_batching_config')
    op.drop_table('course_batching_config')
    op.drop_index(op.f('ix_conflicts_timetable_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_is_resolved'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_conflict_type'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_timetables_status'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_semester_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_is_published'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_dedicated_room_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_time_slots_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_building'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_institutional_rules_rule_type'), table_name='institutional_rules')
    op.drop_index(op.f('ix_institutional_rules_is_active'), table_name='institutional_rules')
    op.drop_index(op.f('ix_institutional_rules_id'), table_name='institutional_rules')
    op.drop_table('institutional_rules')
    op.drop_index(op.f('ix_elective_groups_id'), table_name='elective_groups')
    op.drop_table('elective_groups')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_constraints_id'), table_name='constraints')
    op.drop_table('constraints')
    # ### end Alembic commands ###
