"""Make semester_id nullable in CourseElectiveAssignment

Revision ID: 8563a506ba31
Revises: 2a0f37eaf0c2
Create Date: 2026-03-08 23:16:49.797009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8563a506ba31'
down_revision: Union[str, None] = '2a0f37eaf0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_elective_assignments', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_elective_assignment_group_sem_course', 'course_elective_assignments', type_='unique')
    op.create_unique_constraint('uq_elective_assignment_group_course', 'course_elective_assignments', ['elective_group_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_elective_assignment_group_course', 'course_elective_assignments', type_='unique')
    op.create_unique_constraint('uq_elective_assignment_group_sem_course', 'course_elective_assignments', ['elective_group_id', 'semester_id', 'course_id'])
    op.alter_column('course_elective_assignments', 'semester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
