"""Add time slot columns to faculty_leaves table

Revision ID: add_faculty_leave_time_slots
Revises: 18b3670e77d7
Create Date: 2026-03-08 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'add_faculty_leave_time_slots'
down_revision: Union[str, None] = '18b3670e77d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_leaves', sa.Column('is_full_day', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('faculty_leaves', sa.Column('start_time_slot_id', sa.Integer(), nullable=True))
    op.add_column('faculty_leaves', sa.Column('end_time_slot_id', sa.Integer(), nullable=True))
    op.add_column('faculty_leaves', sa.Column('affected_slot_ids', postgresql.ARRAY(sa.Integer()), nullable=False, server_default='{}'))

    op.create_foreign_key(
        'fk_faculty_leaves_start_time_slot_id',
        'faculty_leaves',
        'time_slots',
        ['start_time_slot_id'],
        ['id'],
        ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_faculty_leaves_end_time_slot_id',
        'faculty_leaves',
        'time_slots',
        ['end_time_slot_id'],
        ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_faculty_leaves_end_time_slot_id', 'faculty_leaves', type_='foreignkey')
    op.drop_constraint('fk_faculty_leaves_start_time_slot_id', 'faculty_leaves', type_='foreignkey')
    op.drop_column('faculty_leaves', 'affected_slot_ids')
    op.drop_column('faculty_leaves', 'end_time_slot_id')
    op.drop_column('faculty_leaves', 'start_time_slot_id')
    op.drop_column('faculty_leaves', 'is_full_day')
    # ### end Alembic commands ###
